### PR TITLE
private apps auth

### PR DESCRIPTION
**Pull request by angel-cuemby**
I was trying to use your module in a private app but i always got connection error i figure out that using the auth option on http works, so implemented, maybe there is another or better way to do it, but this is the one i found, here i'm sharing my solution with you if you want to added. :D

### CODE REVIEW

**Comment by nodeit** [comment]
Do you mind sending along the connection error and the code in question you tried to connect with?

This module already allows for you to connect with a private app using this [code](https://github.com/sinechris/shopify-node-api#note).

I just checked again myself and there were no issues connecting with a private app.

**Comment by sinechris** [comment]
Do you mind sending along the connection error and the code in question you tried to connect with?

This module already allows for you to connect with a private app using this [code](https://github.com/sinechris/shopify-node-api#note).

I just checked again myself and there were no issues connecting with a private app.

**Comment by angel-cuemby** [comment]
@sinechris sorry man i take that back :( i was confuse because the terminology in shopify they say: `https://apikey:password@hostname/admin/resource.json` but in your example code instead of password say's token so was a little confusing i just figure out, my bad. But probably a little clarification in the code would help something like: `access_token: 'token', //permanent token or password for private apps`

**Comment by sinechris** [comment]
No problem at all. I can't get to this right now but if you want to do another pull request just for the new documentation, I'll get it merged in for you.

**Pull request closed without merging**
